name: "Titanium Android build"
description: "Installs Titanium SDK and builds your Android apk debug app"

inputs:
  version:
    description: "The Titanium SDK version you want to install. e.g. 11.1.1.GA"
    required: false
    default: "11.1.1.GA"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Install Titanium SDK
      uses:  m1ga/titanium-install@1.0.0
      with:
        version: ${{ inputs.version }}

    - name: Build app
      run: |
        ti build -p android -b -l info

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my APK
        path: ./build/android/app/build/outputs/apk/debug/app-debug.apk

branding:
  icon: "smartphone"
  color: "red"
